// AI-USAGE SUMMARY
// None of the code in this file was generated by AI.

export function calculateBMI(heightInches, weightPounds) {
    if (!heightInches || heightInches <= 0) return null;
  
    return (weightPounds * 703) / (heightInches * heightInches);
  }
  